### ISSUE TITLE
Support for Latest Casbin.NET Version

### ISSUE THREAD

**Issue by msfreed** [casbin-net/redis-watcher#9]
Are there plans to update to the latest version of Casbin.NET soon to account for the updates to the watcher interfaces? The current release is not compatible with v2.1.1 of Casbin.NET. Thanks

**Comment by hsluoyz** [comment]
@msfreed hi, can you make a PR to fix it?

**Comment by msfreed** [comment]
I gave it a shot https://github.com/casbin-net/redis-watcher/pull/10
